/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-04 23:33:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FormsProduct;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/FormsProduct/../plantillas/header.jsp", Long.valueOf(1693866704000L));
    _jspx_dependants.put("/FormsProduct/../plantillas/footer2.jsp", Long.valueOf(1691986080000L));
    _jspx_dependants.put("/FormsProduct/../plantillas/footer.jsp", Long.valueOf(1691976134000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>InLineManage</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/index.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/main.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/indexModule.css\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/formsUpdate.css\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <script src=\"https://kit.fontawesome.com/8232721784.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Caveat&family=Concert+One&family=Oxygen&family=Playfair:ital,wght@0,300;1,500&family=Wix+Madefor+Display:wght@800&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("    <header>\n");
      out.write("        <img src=\"assets/img/LogoInterline.PNG\" alt=\"LogoInterline\" class=\"logo\">\n");
      out.write("        <h1 class=\"nameInterline\">INTERLINE COMUNICACIONES</h1>\n");
      out.write("        <div class=\"menuUser\">\n");
      out.write("            <div id=\"iconUser\">\n");
      out.write("                <i class=\"fa-solid fa-user\" style=\"color: #000000;\" ></i>\n");
      out.write("            </div>  \n");
      out.write("            <div class=\"userOptions\">\n");
      out.write("                <h3>Bienvenido</h3>\n");
      out.write("                <a href=\"ControllerInline?enviar=index\" class=\"linkMenu\">Cerrar sesión</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("<main class=\"main\" id=\"mainForm\">\n");
      out.write("    <div>\n");
      out.write("        <a href=\"ControllerInline?enviar=product\"><img src=\"assets/img/back.PNG\" alt=\"backlog\" class=\"backlogForm\"></a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <form action=\"ControllerInline\" method=\"post\" id=\"formValidacion\" novalidate>\n");
      out.write("        <h1 class=\"title-table\">Registro de Productos</h1>\n");
      out.write("        <div class=\"contentForm\">\n");
      out.write("\n");
      out.write("            <div class=\"unidadesDisponibles\">\n");
      out.write("                <label for=\"unidadesDisponibles\">Unidades Disponibles:</label>\n");
      out.write("                <input type=\"text\" id=\"unidadesDisponibles\" name=\"unidadesDisponibles\" class=\"inputForm\">\n");
      out.write("                <span class=\"fbForm\">Hola Mundo</span>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"nameProduct\">\n");
      out.write("                <label for=\"nameProduct\">Nombre de producto:</label>\n");
      out.write("                <input type=\"text\" id=\"nameProduct\" name=\"nameProduct\" class=\"inputForm\">\n");
      out.write("                <span class=\"fbForm\">Hola Mundo</span>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("            <div class=\"precio\">\n");
      out.write("                <label for=\"precio\">Precio:</label>\n");
      out.write("                <input type=\"text\" id=\"precio\" name=\"precio\" class=\"inputForm\">\n");
      out.write("                <span class=\"fbForm\">Hola Mundo</span>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("            <div class=\"descripcion\">\n");
      out.write("                <label for=\"descripcion\">Descripcion:</label>\n");
      out.write("                <input type=\"text\" id=\"descripcion\" name=\"descripcion\" class=\"inputForm\">\n");
      out.write("                <span class=\"fbForm\">Hola Mundo</span>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"serial\">\n");
      out.write("                <label for=\"serial\">Numero serial:</label>\n");
      out.write("                <input type=\"text\" id=\"serial\" name=\"serial\" class=\"inputForm\">\n");
      out.write("                <span class=\"fbForm\">Hola Mundo</span>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"garantiaEntrada\">\n");
      out.write("                <label for=\"garantiaEntrada\">Garantia de entrada:</label>\n");
      out.write("                <input type=\"text\" id=\"garantiaEntrada\" name=\"garantiaEntrada\" class=\"inputForm\">\n");
      out.write("                <span class=\"fbForm\">Hola Mundo</span>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"garantiaVentas\">\n");
      out.write("                <label for=\"garantiaVentas\">Garantia de venta:</label>\n");
      out.write("                <input type=\"text\" id=\"garantiaVentas\" name=\"garantiaVentas\" class=\"inputForm\">\n");
      out.write("                <span class=\"fbForm\">Hola Mundo</span>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("            <div class=\"categoria\">\n");
      out.write("                <label for=\"categoria\">Categoria:</label>\n");
      out.write("                <input type=\"text\" id=\"categoria\" name=\"categoria\" class=\"inputForm\">\n");
      out.write("                <span class=\"fbForm\">Hola Mundo</span>\n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("\n");
      out.write("            <div class=\"divBtnForm\">\n");
      out.write("                <button class=\"btnForm\" name=\"enviar\" value=\"registerProduct\">Registrar</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("</main> \n");
      out.write("<footer>\n");
      out.write("    <p>Todos los derechos reservados a InterlineComunicaciones &copy; 2023<p>\n");
      out.write("</footer>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"assets/js/JsProd/registerProd1.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
